// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyahDkNkso6Shhxu7PqZpoTdozzu3MWxo',
    appId: '1:845396966170:web:a3369385d30bd17d1acaa3',
    messagingSenderId: '845396966170',
    projectId: 'chatapp-7b2ff',
    authDomain: 'chatapp-7b2ff.firebaseapp.com',
    storageBucket: 'chatapp-7b2ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHZrw7zXpijnLEzXhTfkXQcFfLqUfjZxg',
    appId: '1:845396966170:android:ea0c20ca39ec8f7b1acaa3',
    messagingSenderId: '845396966170',
    projectId: 'chatapp-7b2ff',
    storageBucket: 'chatapp-7b2ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjdBvM1F1uYuoxYB61XJv0okDawwmeuY',
    appId: '1:845396966170:ios:61542f8acc2c41731acaa3',
    messagingSenderId: '845396966170',
    projectId: 'chatapp-7b2ff',
    storageBucket: 'chatapp-7b2ff.firebasestorage.app',
    androidClientId: '845396966170-b8d4n5dj3kmjfe7qhrj8dsilrselg8d7.apps.googleusercontent.com',
    iosClientId: '845396966170-6rqv480oaa7aqk9lj8lcpkm7fk263jfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjdBvM1F1uYuoxYB61XJv0okDawwmeuY',
    appId: '1:845396966170:ios:61542f8acc2c41731acaa3',
    messagingSenderId: '845396966170',
    projectId: 'chatapp-7b2ff',
    storageBucket: 'chatapp-7b2ff.firebasestorage.app',
    androidClientId: '845396966170-b8d4n5dj3kmjfe7qhrj8dsilrselg8d7.apps.googleusercontent.com',
    iosClientId: '845396966170-6rqv480oaa7aqk9lj8lcpkm7fk263jfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyahDkNkso6Shhxu7PqZpoTdozzu3MWxo',
    appId: '1:845396966170:web:8a9f44aa578449ea1acaa3',
    messagingSenderId: '845396966170',
    projectId: 'chatapp-7b2ff',
    authDomain: 'chatapp-7b2ff.firebaseapp.com',
    storageBucket: 'chatapp-7b2ff.firebasestorage.app',
  );

}